# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-04 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=600)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IncidenceFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=600)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndicatorCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.Category')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.Indicator')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndicatorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_date', models.DateField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('attached_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.IncidenceFile')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.Indicator')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndicatorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=500)),
                ('schedule', models.CharField(max_length=500)),
                ('office_type', models.CharField(max_length=4)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('map_id', models.CharField(max_length=20)),
                ('area', models.TextField(max_length=400000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='office',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.Region'),
        ),
        migrations.AddField(
            model_name='indicatordata',
            name='indicator_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.IndicatorType'),
        ),
        migrations.AddField(
            model_name='indicatordata',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.Office'),
        ),
        migrations.AddField(
            model_name='indicatorcategory',
            name='indicator_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.IndicatorType'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='categories',
            field=models.ManyToManyField(through='dashboard.IndicatorCategory', to='dashboard.Category'),
        ),
        migrations.AddField(
            model_name='categoryweight',
            name='indicator_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.IndicatorType'),
        ),
    ]
