# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 18:47
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndicatorCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.Category')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.Indicator')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndicatorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_date', models.DateField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.Indicator')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndicatorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('location', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('map_id', models.CharField(max_length=20)),
                ('coord_points', django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='office',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.Region'),
        ),
        migrations.AddField(
            model_name='indicatordata',
            name='indicator_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.IndicatorType'),
        ),
        migrations.AddField(
            model_name='indicatordata',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.Office'),
        ),
        migrations.AddField(
            model_name='indicatorcategory',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.Region'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='categories',
            field=models.ManyToManyField(through='dashboard.IndicatorCategory', to='dashboard.Category'),
        ),
    ]
