# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_incidencefile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatordata',
            name='attached_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.IndicatorData', default=1),
        ),
    ]
