# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-22 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20170801_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.Category')),
                ('indicator_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.IndicatorType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
