# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_indicatordata_attached_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatordata',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
