# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-22 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_indicatorcategory_indicator_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='office_type',
            field=models.CharField(default='0', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='office',
            name='schedule',
            field=models.CharField(default='0', max_length=500),
            preserve_default=False,
        ),
    ]
