# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20170830_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidenceFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='indicatordata',
            name='attached_file',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='dashboard.IncidenceFile'),
            preserve_default=False,
        ),
    ]
